#!/usr/bin/env python3

import sys
import argparse
import os
import shutil
import signal
import json
import logging
import copy
import uuid
import string
from pathlib import Path
from PyQt5.Qt import *
from PyQt5 import QtCore

app_name = "thinkdo"

start_tree = {
    "cursor": "0d1fb54fd3194007835202d076d81e59",
    "nodes": [
        {
            "uniq_id": "21198391c2de42f08f0d935116d15be8",
            "title": "Create todo list",
            "icon": "check_box_uncheck.png",
            "checked": True,
            "expanded": True,
            "auto_collapse": False,
            "children": []
        },
        {
            "uniq_id": "0d1fb54fd3194007835202d076d81e59",
            "title": "Buy bread",
            "icon": "check_box_uncheck.png",
            "checked": False,
            "expanded": True,
            "auto_collapse": False,
            "children": []
        }
    ]
}

# Order matters. Key with the most modifiers should be above those with less.
keypress_items = [
    {"key": Qt.Key_A, "action": "edit"},
    {"key": Qt.Key_C, "action": "toggle_auto_collapse", "modifiers": int(Qt.ShiftModifier)},
    {"key": Qt.Key_C, "action": "toggle_expanded"},
    {"key": Qt.Key_D, "action": "delete"},
    {"key": Qt.Key_E, "action": "export"},
    {"key": Qt.Key_H, "action": "cursor_left"},
    {"key": Qt.Key_J, "action": "move_down_group", "modifiers": int(Qt.ShiftModifier | Qt.ControlModifier)},
    {"key": Qt.Key_J, "action": "move_down", "modifiers": int(Qt.ShiftModifier)},
    {"key": Qt.Key_J, "action": "cursor_down"},
    {"key": Qt.Key_K, "action": "move_up_group", "modifiers": int(Qt.ShiftModifier | Qt.ControlModifier)},
    {"key": Qt.Key_K, "action": "move_up", "modifiers": int(Qt.ShiftModifier)},
    {"key": Qt.Key_K, "action": "cursor_up"},
    {"key": Qt.Key_L, "action": "cursor_right"},
    {"key": Qt.Key_N, "action": "search_next"},
    {"key": Qt.Key_M, "action": "mark_set"},
    {"key": Qt.Key_O, "action": "insert_above", "modifiers": int(Qt.ShiftModifier)},
    {"key": Qt.Key_O, "action": "insert_below"},
    {"key": Qt.Key_P, "action": "paste_into", "modifiers": int(Qt.ShiftModifier | Qt.ControlModifier)},
    {"key": Qt.Key_P, "action": "paste_above", "modifiers": int(Qt.ShiftModifier)},
    {"key": Qt.Key_P, "action": "paste_below"},
    {"key": Qt.Key_Q, "action": "close"},
    {"key": Qt.Key_S, "action": "save"},
    {"key": Qt.Key_V, "action": "toggle_mode_select"},
    {"key": Qt.Key_X, "action": "toggle_done"},
    {"key": Qt.Key_Z, "action": "dump"},
    {"key": Qt.Key_QuoteLeft, "action": "mark_go"},
    {"key": Qt.Key_Escape, "action": "escape"},
    {"key": Qt.Key_Slash, "action": "search"},
    {"key": Qt.Key_Space, "action": "select"},
]

quick_icon_map = {
    "i ": "information.png",
    "! ": "warning.png",
    "+ ": "plus.png",
    "/ ": "folder.png",
    "? ": "question.png",
    "B ": "bug.png",
    "> ": "arrow_right.png",
    "* ": "bullet_black.png",
    "*g ": "bullet_green.png",
    "*b ": "bullet_blue.png",
    "*o ": "bullet_orange.png",
    "*r ": "bullet_red.png",
    "*p ": "bullet_purple.png",
    ": ": "clock.png",
    ">< ": "hourglass.png",
    "<- ": "recur.png",
    ".. ": "progressbar.png",
    "^ ": "note.png",
    "!! ": "exclamation.png",
    "[] ": "check_box_uncheck.png",
    "db ": "database.png",
    "doc ": "document_editing.png",
    "usr ": "user.png",
    "ph ": "phone.png",
}

MODE_NORMAL = 0
MODE_SELECT = 1
MODE_MARK = 2
MODE_MARK_GO = 3

ICON_PATH = os.path.join(os.path.dirname(os.path.realpath(sys.argv[0])), "icons")

class Node:
    """
    Nodes represent a single leaf in the outline tree.
    """
    def __init__(self, title, icon=None, checked=False, expanded=False,
                 auto_collapse=False, uniq_id=None):
        self.title = title
        self.icon = icon
        self.checked = checked
        self.expanded = expanded
        self.auto_collapse = auto_collapse
        if uniq_id is not None:
            self.uniq_id = uniq_id
        else:
            self.uniq_id = uuid.uuid4().hex

    def get_icon(self):
        """
        Return the icon that should currently be used for this node.
        """
        if self.checked is True:
            return "check_box.png"
        else:
            return self.icon

    def copy(self):
        """
        Create a deep-copy of this node, and reset the checked state.
        """
        new_node = Node.from_dict(self.to_dict())
        new_node.uniq_id = uuid.uuid4().hex
        if new_node.checked is True:
            new_node.checked = False
        return new_node

    @staticmethod
    def from_dict(d):
        """
        Convert a dictionary representation of a node into an object
        of type Node.
        """
        node = Node(
            title=d["title"],
            icon=d["icon"],
            checked=d.get("checked", False),
            expanded=d.get("expanded", True),
            auto_collapse=d.get("auto_collapse", False),
            uniq_id=d.get("uniq_id", None),
        )

        return node

    def to_dict(self):
        """
        Convert this node to a dictionary representation.
        """
        s = {
            "uniq_id": self.uniq_id,
            "title": self.title,
            "icon": self.icon,
            "checked": self.checked,
            "expanded": self.expanded,
            "auto_collapse": self.auto_collapse,
        }

        return s

    def to_item(self):
        """
        Convert this Node to a QStandardItem.
        """
        icon = QIcon(os.path.join(ICON_PATH, self.get_icon()))
        item = QStandardItem(icon, self.title)
        item.setData(self)
        return item

    def __repr__(self):
        return "<Node uniq_id='{}', title='{}', icon={}, checked={}, expanded={} auto_collapse={}>".format(
            self.uniq_id, self.title, self.icon, self.checked, self.expanded, self.auto_collapse
        )


class GUI:
    """
    Main GUI class.
    """
    def __init__(self, path, cursor_start=None):
        self.path = path
        self.cursor_start = cursor_start
        self.settings = QSettings("electricmonk", app_name)
        self.cursor = None
        self.mode = MODE_NORMAL
        self.mode_select_cursor = None
        self.del_buf = None
        self.search_results = None
        self.marks = {}

        # Main window
        self.win = QMainWindow()
        self.win.setWindowIcon(QIcon(os.path.join(ICON_PATH, "..", "thinkndo.png")))
        self.win.setWindowTitle("Think'n'Do")
        geometry = self.settings.value("geometry")
        if geometry is not None:
            self.win.restoreGeometry(geometry);

        self.win.closeEvent = self._act_close

        # Node tree
        self.node_view = QTreeView(self.win)
        self.node_view.setWordWrap(True)
        self.node_model = QStandardItemModel(0, 1)
        self.node_model.setHorizontalHeaderLabels(
            [
                "",
            ]
        )
        self.node_view.setModel(self.node_model)
        self.node_root = self.node_model.invisibleRootItem()

        self.load(self.path)

        # Monkey-patch QTreeView. This would be cleaner of it used
        # inheritence, but would complicate the code.
        self.orig_node_view_keyPressEvent = self.node_view.keyPressEvent
        self.node_view.keyPressEvent = self.keyPressEvent
        self.orig_node_view_closeEditor = self.node_view.closeEditor
        self.node_view.closeEditor = self.closeEditor

        # Signals
        self.node_view.expanded.connect(self._ev_expanded)
        self.node_view.collapsed.connect(self._ev_collapsed)
        self.node_view.selectionModel().currentChanged.connect(self._ev_current_changed)
        self.node_model.itemChanged.connect(self._ev_item_changed)

        # Jump to given cursor
        if self.cursor_start is not None:
            self.go_uniq_id(self.cursor_start)

        self.win.setCentralWidget(self.node_view)
        self.win.show()

    def close(self):
        self.save(self.path)
        self.settings.setValue("geometry", self.win.saveGeometry())
        self.settings.sync()
        QCoreApplication.quit()

    def load(self, path):
        """
        Load a tree from a JSON file.
        """
        with open(path, "r") as f:
            tnd = json.load(f)

        self.cursor = tnd.get("cursor", None)
        self.marks = tnd.get("marks", {})
        self.deserialize(tnd["nodes"], self.node_root)

    def save(self, path):
        """
        Save a tree to a JSON file.
        """
        raw_nodes = self.serialize(self.node_root)
        tnd = {
            "cursor": self.cursor,
            "marks": self.marks,
            "nodes": raw_nodes
        }

        with open(path, "w") as f:
            json.dump(tnd, f, indent=2)

    def serialize(self, parent):
        """
        Serialize the QStandardItem `parent`, including its children to a
        Python dicts
        """
        raw_nodes = []
        for i in range(0, parent.rowCount()):
            item = parent.child(i)
            node = item.data()
            raw_node = node.to_dict()
            raw_nodes.append(raw_node)
            raw_node["children"] = self.serialize(item)

        return raw_nodes

    def deserialize(self, l, parent, row=None):
        """
        Deserialize dicts in list `l` into QStandardItemModels under `parent`.
        The dicts in `l` are converted to instances of Node() which are set as
        data on each of the items in the tree.
        """
        for child in l:
            node = Node.from_dict(child)
            tree = self.insert_node(node, parent)
            self.deserialize(child["children"], tree)

    def insert_node(self, node, parent, row=None):
        """
        Insert a node into the tree. `parent` is a QStandardItem. Returns the
        newly created QStandardItem.
        """
        item = node.to_item()
        row_items = [item]

        if row is None:
            # Append at end of current level
            parent.appendRow(row_items)
            cur_item = parent.child(parent.rowCount() - 1)
        else:
            # Append at specified row
            parent.insertRow(row, row_items)

        index = self.node_model.indexFromItem(item)
        if node.expanded is True and node.auto_collapse is False:
            self.node_view.setExpanded(index, True)

        if node.uniq_id == self.cursor:
            self.node_view.setCurrentIndex(index)

        return item

    def get(self, index=None):
        """
        Return index, item, node, etc for `index`. If `index` is not given, it
        returns the currently selected index.
        """
        if index is None:
            index = self.node_view.currentIndex()
        item = self.node_model.itemFromIndex(index)
        if item is None:
            return None
        node = item.data()
        row = index.row()
        parent_item = item.parent()
        if parent_item is None:
            parent_item = self.node_root
        parent_index = index.parent()

        return {
            "index": index,
            "item": item,
            "node": node,
            "row": row,
            "parent_item": parent_item
        }

    def get_sel(self):
        """
        Return a list of all selected nodes.
        """
        sel_model = self.node_view.selectionModel()
        nodes = []
        for index in reversed(sel_model.selectedIndexes()):
            nodes.append(self.get(index))
        return nodes

    def get_uniq_id(self, uniq_id, parent=None):
        """
        Find an item in the tree by its Node.uniq_id
        """
        if parent is None:
            parent = self.node_root

        for i in range(0, parent.rowCount()):
            item = parent.child(i)
            node = item.data()
            if node.uniq_id == uniq_id:
                return item
            ret = self.get_uniq_id(uniq_id, item)
            if ret is not None:
                return ret

        return None

    def closeEditor(self, editor, hint):
        self.orig_node_view_closeEditor(editor, hint)
        if editor.text() == "":
            cur = self.get()
            self.node_model.removeRows(cur["index"].row(), 1, cur["index"].parent())

    def search(self, text, parent=None):
        """
        Show a text-entry dialog window and search for the entered text.
        """
        if parent is None:
            parent = self.node_model.invisibleRootItem()

        results = []
        for i in range(0, parent.rowCount()):
            child = parent.child(i)
            node = child.data()
            if text.lower() in node.title.lower():
                results.append(child)
            results.extend(self.search(text, child))
        return results

    def go_uniq_id(self, uniq_id):
        """
        Set the cursor to the QStandardItem with uniq_id.
        """
        item = self.get_uniq_id(uniq_id)
        if item is not None:
            new_index = self.node_model.indexFromItem(item)
            self.node_view.setCurrentIndex(new_index)

    def mark_set(self, letter):
        cur = self.get()
        self.marks[letter] = cur["node"].uniq_id
        self.set_mode(MODE_NORMAL)

    def mark_go(self, letter):
        mark_uniq_id = self.marks.get(letter, None)
        if mark_uniq_id is not None:
            self.go_uniq_id(mark_uniq_id)

        self.set_mode(MODE_NORMAL)

    def set_mode(self, mode):
        """
        Switch modes.
        """
        self.mode = mode

        if mode == MODE_NORMAL:
            # Reset everything to normal mode
            cur = self.get()
            self.mode = MODE_NORMAL
            sel_model = self.node_view.selectionModel()
            self.node_view.setCurrentIndex(cur["index"])
            sel_model.select(cur["index"], QItemSelectionModel.Select)
            self.mode_select_cursor = None

    def keyPressEvent(self, keypress):
        """
        Handle key press events. Looks in `keypress_items` for actions.
        """
        if self.mode == MODE_MARK:
            letter = keypress.text()
            if letter != "" and letter in string.ascii_letters:
                self.mark_set(letter)
                return
            elif keypress.key() != Qt.Key_Escape:
                return
        elif self.mode == MODE_MARK_GO:
            letter = keypress.text()
            if letter != "" and letter in string.ascii_letters:
                self.mark_go(letter)
                return
            elif keypress.key() != Qt.Key_Escape:
                return

        for keypress_item in keypress_items:
            if (
                keypress.key() == keypress_item["key"] and
                (
                    "modifiers" not in keypress_item or
                    (int(keypress.modifiers()) & keypress_item["modifiers"] == keypress_item["modifiers"])
                )
               ):
                action_cb = getattr(self, "_act_{}".format(keypress_item["action"]))
                action_cb()
                return
        self.orig_node_view_keyPressEvent(keypress)

    def _ev_expanded(self, index):
        cur = self.get(index)
        cur["node"].expanded = True
        self.save(self.path)

    def _ev_collapsed(self, index):
        item = self.get(index)
        item["node"].expanded = False
        self.save(self.path)

    def _ev_current_changed(self, new_index, prev_index):
        """
        Auto-collapse trees if user moves away from them.
        """
        new = self.get(new_index)
        prev = self.get(prev_index)

        assert new_index is not None
        if prev is None:
            return

        # Build a list of items that shouldn't be collapsed, because they're
        # parents of the new item we're switching to.
        no_collapse = []
        i = new
        while i is not None:
            if i is prev["item"]:
                return
            i = self.get(i["index"].parent())
            no_collapse.append(i)

        # Collapse previous item and all its parents, except if they're a
        # parent of the new item
        item = prev
        while item is not None:
            if item not in no_collapse and item["node"].auto_collapse is True:
                self.node_view.setExpanded(item["index"], False)
            item = self.get(item["index"].parent())

        # Set cursor to new item uniq_id
        self.cursor = new["node"].uniq_id

    def _ev_item_changed(self, item):
        logging.info("ev_item_changed: {}".format(item))
        index = self.node_model.indexFromItem(item)
        cur = self.get(index)
        text = item.text()

        cur["node"].title = text

        # Check for quick-icon-mapping where the user can start the title with
        # certain chars to change the icon.
        for key in quick_icon_map.keys():
            if text.startswith(key):
                new_text = text[len(key):]
                cur["node"].icon = quick_icon_map[key]
                cur["node"].title = new_text
                cur["node"].checked = False
                item.setText(new_text)
                item.setIcon(QIcon(os.path.join(ICON_PATH, quick_icon_map[key])))
                break

        self.save(self.path)

    def _act_close(self, event=None):
        """
        Catch the user pressing the [X] button and cleanly close the app.
        """
        self.close()

    def _act_cursor_up(self):
        if self.mode == MODE_NORMAL:
            # Move cursor up
            cur = self.get()
            new_index = cur["index"].siblingAtRow(cur["index"].row() - 1)
            if new_index.row() != -1:
                self.node_view.setCurrentIndex(new_index)
        elif self.mode == MODE_SELECT:
            # Grow selection down
            self.mode_select_cursor = self.get(self.mode_select_cursor)
            cursor = self.mode_select_cursor
            if cursor is None:
                return
            next_index = cursor["index"].siblingAtRow(cursor["index"].row() - 1)
            sel_model = self.node_view.selectionModel()
            sel_model.select(next_index, QItemSelectionModel.Select)
            self.mode_select_cursor  = next_index

    def _act_cursor_down(self):
        if self.mode == MODE_NORMAL:
            # Move cursor down
            cur = self.get()
            new_index = cur["index"].siblingAtRow(cur["index"].row() + 1)
            if new_index.row() != -1:
                self.node_view.setCurrentIndex(new_index)
        elif self.mode == MODE_SELECT:
            # Grow selection down
            self.mode_select_cursor = self.get(self.mode_select_cursor)
            cursor = self.mode_select_cursor
            if cursor is None:
                return
            next_index = cursor["index"].siblingAtRow(cursor["index"].row() + 1)
            sel_model = self.node_view.selectionModel()
            sel_model.select(next_index, QItemSelectionModel.Select)
            self.mode_select_cursor  = next_index

    def _act_cursor_left(self):
        cur = self.get()
        new_index = self.node_model.indexFromItem(cur["parent_item"])

        # Focus
        if cur["item"].parent() is not None:
            self.node_view.setCurrentIndex(new_index)

    def _act_cursor_right(self):
        cur = self.get()
        has_children = self.node_model.hasChildren(cur["index"])

        if not has_children:
            # Add new child
            new_node = cur["node"].copy()
            new_node.title = ""
            new_item = self.insert_node(new_node, cur["item"])
            new_index = self.node_model.indexFromItem(new_item)

            # Edit the new node
            self.node_view.setCurrentIndex(new_index)
            self.node_view.edit(new_index)
        else:
            # Move into subtree
            self.node_view.setExpanded(cur["index"], True)
            new_index = self.node_view.moveCursor(QAbstractItemView.MoveRight,
                                                  Qt.NoModifier)
            self.node_view.setCurrentIndex(new_index)

    def _act_dump(self):
        print("cur")
        print(70 * "-")
        cur = self.get()
        sys.stdout.write(repr(cur) + "\n")
        sys.stdout.flush()

        print("cur['item']")
        print(70 * "-")
        print(self.serialize(cur["item"]))

        print("del_buf")
        print(70 * "-")
        print(json.dumps(self.del_buf, indent=2))

    def _act_delete(self):
        self.del_buf = []
        selected = self.get_sel()

        # Serialize selected items into delete buffer
        for s in selected:
            node_dict = s["node"].to_dict()
            node_dict["children"] = self.serialize(s["item"])
            self.del_buf.append(node_dict)

        # Remove selected rows
        for s in selected:
            self.node_model.removeRows(s["index"].row(), 1, s["index"].parent())

        # Go back to normal mode and save
        self.set_mode(MODE_NORMAL)
        self.save(self.path)

    def _act_edit(self):
        cur = self.get()
        self.node_view.edit(cur["index"])

    def _act_escape(self):
        """
        Handle the escape key by switching back to normal mode or quiting the
        application.
        """
        if self.mode != MODE_NORMAL:
            self.set_mode(MODE_NORMAL)
        else:
            self._act_close()

    def _act_export(self):
        print('export')

    def _act_insert_above(self):
        cur = self.get()
        cur_row = cur["index"].row()
        if cur_row > 0:
            prev = self.get(cur["index"].siblingAtRow(cur_row - 1))
        else:
            prev = self.get(cur["index"].siblingAtRow(0))

        # Create new node and insert
        new_node = prev["node"].copy()
        new_node.title = ""
        new_item = self.insert_node(new_node, cur["parent_item"], cur["row"])
        new_index = self.node_model.indexFromItem(new_item)

        # Edit the new node
        self.node_view.setCurrentIndex(new_index)
        self.node_view.edit(new_index)

    def _act_insert_below(self):
        cur = self.get()

        # Create new node and insert
        new_node = cur["node"].copy()
        new_node.title = ""
        new_item = self.insert_node(new_node, cur["parent_item"], cur["row"] + 1)
        new_index = self.node_model.indexFromItem(new_item)

        # Edit the new node
        self.node_view.setCurrentIndex(new_index)
        self.node_view.edit(new_index)

    def _act_mark_set(self):
        self.set_mode(MODE_MARK)

    def _act_mark_go(self):
        self.set_mode(MODE_MARK_GO)

    def _act_move_up(self):
        cur = self.get()
        children = self.serialize(cur["item"])
        cur_row = cur["item"].row()
        cur_index_parent = cur["index"].parent()

        if cur_row == 0:
            # First item in list
            return

        self.node_model.removeRows(cur_row, 1, cur_index_parent)
        new_item = self.insert_node(cur["node"], cur["parent_item"], cur_row - 1)
        self.deserialize(children, new_item)
        new_index = self.node_model.indexFromItem(new_item)
        self.node_view.setCurrentIndex(new_index)
        cur_index = self.node_view.currentIndex()
        cur_item = self.node_model.itemFromIndex(cur_index)

    def _act_move_up_group(self):
        """
        Move the current item up to the first item
        that matches its icon on checked state.
        """
        cur = self.get()
        children = self.serialize(cur["item"])
        cur_row = cur["item"].row()
        cur_index_parent = cur["index"].parent()

        inspect_row = cur_row - 1
        match_found = False
        while inspect_row > -1:
            inspect = cur["parent_item"].child(inspect_row).data()

            if cur["node"].checked is True:
                if inspect.checked is True:
                    match_found = True
                    break
            else:
                if cur["node"].icon == inspect.icon:
                    match_found = True
                    break
            inspect_row -= 1

        self.node_model.removeRows(cur_row, 1, cur_index_parent)
        if match_found is True:
            new_item = self.insert_node(cur["node"], cur["parent_item"], inspect_row + 1)
        else:
            new_item = self.insert_node(cur["node"], cur["parent_item"], 0)
        self.deserialize(children, new_item)
        new_index = self.node_model.indexFromItem(new_item)
        self.node_view.setCurrentIndex(new_index)


    def _act_move_down_group(self):
        """
        Move the current item down to the first item
        that matches its icon on checked state.
        """
        cur = self.get()
        children = self.serialize(cur["item"])
        cur_row = cur["item"].row()
        cur_index_parent = cur["index"].parent()

        inspect_row = cur_row + 1
        while inspect_row != cur["parent_item"].rowCount():
            inspect = cur["parent_item"].child(inspect_row).data()

            if cur["node"].checked is True:
                if inspect.checked is True:
                    break
            else:
                if cur["node"].icon == inspect.icon:
                    break
            inspect_row += 1

        self.node_model.removeRows(cur_row, 1, cur_index_parent)
        new_item = self.insert_node(cur["node"], cur["parent_item"], inspect_row - 1)
        self.deserialize(children, new_item)
        new_index = self.node_model.indexFromItem(new_item)
        self.node_view.setCurrentIndex(new_index)

    def _act_move_down(self):
        cur = self.get()
        children = self.serialize(cur["item"])
        cur_row = cur["item"].row()
        cur_index_parent = cur["index"].parent()

        if (cur_row + 1) == cur["parent_item"].rowCount():
            # Last item in list
            return

        self.node_model.removeRows(cur_row, 1, cur_index_parent)
        new_item = self.insert_node(cur["node"], cur["parent_item"], cur_row + 1)
        self.deserialize(children, new_item)
        new_index = self.node_model.indexFromItem(new_item)
        self.node_view.setCurrentIndex(new_index)

    def _act_paste_above(self):
        if self.del_buf is None:
            return

        cur = self.get()
        cur_row = cur["item"].row()

        for row in self.del_buf:
            node = Node.from_dict(row)
            new_item = self.insert_node(node, cur["parent_item"], cur_row)
            self.deserialize(row["children"], new_item)

    def _act_paste_below(self):
        if self.del_buf is None:
            return

        cur = self.get()
        cur_row = cur["item"].row()

        for row in self.del_buf:
            node = Node.from_dict(row)
            new_item = self.insert_node(node, cur["parent_item"], cur_row + 1)
            self.deserialize(row["children"], new_item)

    def _act_paste_into(self):
        if self.del_buf is None:
            return

        cur = self.get()

        for row in self.del_buf:
            node = Node.from_dict(row)
            new_item = self.insert_node(node, cur["item"], 0)
            self.deserialize(row["children"], new_item)

    def _act_search(self):
        """
        Activate search
        """
        search, action = QInputDialog.getText(None, "Search", "Search term", QLineEdit.Normal, "")
        if action == False:
            return

        results = self.search(search)
        if results:
            self.search_results = results
            self._act_search_next()

    def _act_search_next(self):
        if self.search_results is None:
            return

        # Ring buffer the search results
        result = self.search_results.pop(0)
        self.search_results.append(result)
        new_index = self.node_model.indexFromItem(result)
        self.node_view.setCurrentIndex(new_index)

    def _act_save(self):
        self.save(self.path)

    def _act_toggle_auto_collapse(self):
        cur = self.get()
        cur["node"].auto_collapse = not cur["node"].auto_collapse
        if cur["node"].auto_collapse is True:
            self.node_view.setExpanded(cur["index"], False)

    def _act_toggle_done(self):
        """
        Toggle t he current node as "Done".
        """
        sel = self.get_sel()
        for n in sel:
            n["node"].checked = not n["node"].checked
            n["item"].setIcon(QIcon(os.path.join(ICON_PATH, n["node"].get_icon())))

        self.set_mode(MODE_NORMAL)
        self.save(self.path)

    def _act_toggle_expanded(self):
        cur = self.get()
        inv_expanded = not self.node_view.isExpanded(cur["index"])
        self.node_view.setExpanded(cur["index"], inv_expanded)

    def _act_toggle_mode_select(self):
        """
        Switch between select mode and normal mode.
        """
        if self.mode == MODE_NORMAL:
            self.set_mode(MODE_SELECT)
        else:
            self.set_mode(MODE_NORMAL)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--debug",
                        dest='debug',
                        action="store_true")
    parser.add_argument("-c", "--cursor",
                        metavar='ID',
                        type=str,
                        dest='cursor',
                        help="Jump cursor to item ID")
    parser.add_argument(metavar='PATH',
                        dest='path',
                        type=str)
    args = parser.parse_args()

    # Make sure ctrl-c on the commandline stops the application
    signal.signal(signal.SIGINT, signal.SIG_DFL)

    if args.debug is True:
        logging.basicConfig(level=logging.DEBUG)
    else:
        logging.basicConfig(level=logging.WARN)

    # Create new file if it doesn't exist yet.
    if os.path.exists(args.path) is False:
        with open(args.path, "w") as f:
            json.dump(start_tree, f, indent=2)
    else:
        # Backup file
        shutil.copy2(args.path, "{}.bak".format(args.path))

    # Lock file
    lock_path = "{}.lock".format(args.path)
    if os.path.isfile(lock_path):
        sys.stderr.write("{} found. Aborting\n".format(lock_path))
        sys.exit(1)
    Path(lock_path).touch()

    # GUI
    app = QApplication([])
    gui = GUI(args.path, args.cursor)
    app.exec_()

    # Unlock
    os.unlink(lock_path)
